# 公共配置文件
# @author <a href="https://github.com/liyao">程序员鱼皮</a>
# @from <a href="https://yao.icu">编程导航知识星球</a>
server:
  port: 8123
  servlet:
    context-path: /api
yuapi:
  client:
    access-key: yao
    secret-key: abcdefgh