# 线上配置文件

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.14.155.37:3306/api_center
    username: root
    password: 56xj7tNt5wZYFDes
  cloud:
    sentinel:
      transport:
        dashboard: 1.14.155.37:9090

